// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3pH2KnTggIaWlPF6KpYSpOxGZve4OSE',
    appId: '1:134672670297:web:af043eaf66f84d02d1db48',
    messagingSenderId: '134672670297',
    projectId: 'taller-3-universidades',
    authDomain: 'taller-3-universidades.firebaseapp.com',
    storageBucket: 'taller-3-universidades.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACFn2hdZIz4A-wbVQkGWumBsm08A4mW_g',
    appId: '1:134672670297:android:b7cf244d5d28f263d1db48',
    messagingSenderId: '134672670297',
    projectId: 'taller-3-universidades',
    storageBucket: 'taller-3-universidades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_nDMRsuPmt9aDnGxDYNHGiV4olTrPaA',
    appId: '1:134672670297:ios:924090505697dac5d1db48',
    messagingSenderId: '134672670297',
    projectId: 'taller-3-universidades',
    storageBucket: 'taller-3-universidades.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_nDMRsuPmt9aDnGxDYNHGiV4olTrPaA',
    appId: '1:134672670297:ios:924090505697dac5d1db48',
    messagingSenderId: '134672670297',
    projectId: 'taller-3-universidades',
    storageBucket: 'taller-3-universidades.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-3pH2KnTggIaWlPF6KpYSpOxGZve4OSE',
    appId: '1:134672670297:web:2e4cba91f640eca8d1db48',
    messagingSenderId: '134672670297',
    projectId: 'taller-3-universidades',
    authDomain: 'taller-3-universidades.firebaseapp.com',
    storageBucket: 'taller-3-universidades.firebasestorage.app',
  );
}
